// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Address,
  Bytes,
  BigInt,
  BigDecimal
} from "@graphprotocol/graph-ts";

export class Block extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Block entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Block entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Block", id.toString(), this);
  }

  static load(id: string): Block | null {
    return store.get("Block", id) as Block | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get parentHash(): Bytes {
    let value = this.get("parentHash");
    return value.toBytes();
  }

  set parentHash(value: Bytes) {
    this.set("parentHash", Value.fromBytes(value));
  }

  get unclesHash(): Bytes {
    let value = this.get("unclesHash");
    return value.toBytes();
  }

  set unclesHash(value: Bytes) {
    this.set("unclesHash", Value.fromBytes(value));
  }

  get author(): Bytes {
    let value = this.get("author");
    return value.toBytes();
  }

  set author(value: Bytes) {
    this.set("author", Value.fromBytes(value));
  }

  get stateRoot(): Bytes {
    let value = this.get("stateRoot");
    return value.toBytes();
  }

  set stateRoot(value: Bytes) {
    this.set("stateRoot", Value.fromBytes(value));
  }

  get transactionsRoot(): Bytes {
    let value = this.get("transactionsRoot");
    return value.toBytes();
  }

  set transactionsRoot(value: Bytes) {
    this.set("transactionsRoot", Value.fromBytes(value));
  }

  get receiptsRoot(): Bytes {
    let value = this.get("receiptsRoot");
    return value.toBytes();
  }

  set receiptsRoot(value: Bytes) {
    this.set("receiptsRoot", Value.fromBytes(value));
  }

  get number(): BigInt {
    let value = this.get("number");
    return value.toBigInt();
  }

  set number(value: BigInt) {
    this.set("number", Value.fromBigInt(value));
  }

  get gasUsed(): BigInt {
    let value = this.get("gasUsed");
    return value.toBigInt();
  }

  set gasUsed(value: BigInt) {
    this.set("gasUsed", Value.fromBigInt(value));
  }

  get gasLimit(): BigInt {
    let value = this.get("gasLimit");
    return value.toBigInt();
  }

  set gasLimit(value: BigInt) {
    this.set("gasLimit", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get difficulty(): BigInt {
    let value = this.get("difficulty");
    return value.toBigInt();
  }

  set difficulty(value: BigInt) {
    this.set("difficulty", Value.fromBigInt(value));
  }

  get totalDifficulty(): BigInt {
    let value = this.get("totalDifficulty");
    return value.toBigInt();
  }

  set totalDifficulty(value: BigInt) {
    this.set("totalDifficulty", Value.fromBigInt(value));
  }

  get size(): BigInt | null {
    let value = this.get("size");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set size(value: BigInt | null) {
    if (value === null) {
      this.unset("size");
    } else {
      this.set("size", Value.fromBigInt(value as BigInt));
    }
  }
}

export class NewEpochParam extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save NewEpochParam entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save NewEpochParam entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("NewEpochParam", id.toString(), this);
  }

  static load(id: string): NewEpochParam | null {
    return store.get("NewEpochParam", id) as NewEpochParam | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get epochId(): BigInt {
    let value = this.get("epochId");
    return value.toBigInt();
  }

  set epochId(value: BigInt) {
    this.set("epochId", Value.fromBigInt(value));
  }

  get startBlock(): BigInt {
    let value = this.get("startBlock");
    return value.toBigInt();
  }

  set startBlock(value: BigInt) {
    this.set("startBlock", Value.fromBigInt(value));
  }

  get endBlock(): BigInt {
    let value = this.get("endBlock");
    return value.toBigInt();
  }

  set endBlock(value: BigInt) {
    this.set("endBlock", Value.fromBigInt(value));
  }

  get signer(): string {
    let value = this.get("signer");
    return value.toString();
  }

  set signer(value: string) {
    this.set("signer", Value.fromString(value));
  }
}

export class ReCommitEpochParam extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save ReCommitEpochParam entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save ReCommitEpochParam entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("ReCommitEpochParam", id.toString(), this);
  }

  static load(id: string): ReCommitEpochParam | null {
    return store.get("ReCommitEpochParam", id) as ReCommitEpochParam | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get oldEpochId(): BigInt {
    let value = this.get("oldEpochId");
    return value.toBigInt();
  }

  set oldEpochId(value: BigInt) {
    this.set("oldEpochId", Value.fromBigInt(value));
  }

  get newEpochId(): BigInt {
    let value = this.get("newEpochId");
    return value.toBigInt();
  }

  set newEpochId(value: BigInt) {
    this.set("newEpochId", Value.fromBigInt(value));
  }

  get startBlock(): BigInt {
    let value = this.get("startBlock");
    return value.toBigInt();
  }

  set startBlock(value: BigInt) {
    this.set("startBlock", Value.fromBigInt(value));
  }

  get endBlock(): BigInt {
    let value = this.get("endBlock");
    return value.toBigInt();
  }

  set endBlock(value: BigInt) {
    this.set("endBlock", Value.fromBigInt(value));
  }

  get newSigner(): string {
    let value = this.get("newSigner");
    return value.toString();
  }

  set newSigner(value: string) {
    this.set("newSigner", Value.fromString(value));
  }
}

export class UserEpochParam extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save UserEpochParam entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save UserEpochParam entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("UserEpochParam", id.toString(), this);
  }

  static load(id: string): UserEpochParam | null {
    return store.get("UserEpochParam", id) as UserEpochParam | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get epochId(): BigInt {
    let value = this.get("epochId");
    return value.toBigInt();
  }

  set epochId(value: BigInt) {
    this.set("epochId", Value.fromBigInt(value));
  }

  get startBlock(): BigInt {
    let value = this.get("startBlock");
    return value.toBigInt();
  }

  set startBlock(value: BigInt) {
    this.set("startBlock", Value.fromBigInt(value));
  }

  get endBlock(): BigInt {
    let value = this.get("endBlock");
    return value.toBigInt();
  }

  set endBlock(value: BigInt) {
    this.set("endBlock", Value.fromBigInt(value));
  }

  get signer(): string {
    let value = this.get("signer");
    return value.toString();
  }

  set signer(value: string) {
    this.set("signer", Value.fromString(value));
  }

  get active(): boolean {
    let value = this.get("active");
    return value.toBoolean();
  }

  set active(value: boolean) {
    this.set("active", Value.fromBoolean(value));
  }
}
