version: '3'
services:
  graph-node1:
    image: graphprotocol/graph-node:v0.31.0-rc.1
    ports:
      - '7000:8000'
      - '7001:8001'
      - '7020:8020'
      - '7030:8030'
      - '7040:8040'
    depends_on:
      - ipfs1
      - postgres1
    environment:
      postgres_host: postgres1
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs1:5001'
      ethereum: 'mainnet:http://3.213.188.165:8545'
      GRAPH_LOG: info
    restart: always
  ipfs1:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '4001:5001'
    volumes:
      - /data/graph-node2/ipfs:/data/ipfs
    restart: always
  postgres1:
    image: postgres
    ports:
      - '4432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - /data/graph-node2/postgres:/var/lib/postgresql/data
    restart: always